"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/AISC_Workshop1.ipynb"
"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/Capstone Project Course.ipynb"
"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/Week 3 Capstone - Segmenting and Clustering Neighbourhoods in Toronto.ipynb"
"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/Week 3 Capstone - Segmenting and Clustering Neighbourhoods in Toronto_Part 2.ipynb"
"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/Week 4 Capstone - Segmenting and Clustering Neighbourhoods in Fredericton - Github submit.ipynb"
"./Applied-Data-Science-Capstone-master.zip.dir/Applied-Data-Science-Capstone-master/Week 5 Capstone Report - Segmenting and Clustering Neighbourhoods in Fredericton-Github Submit.ipynb"
"./Capstone.ipynb"
"./CapstoneProject-master.zip.dir/CapstoneProject-master/BattleofNeighborhood.ipynb"
"./CapstoneProject-master.zip.dir/CapstoneProject-master/Capstone1.ipynb"
"./CapstoneProject-master.zip.dir/CapstoneProject-master/Capstone2.ipynb"
"./Capstone_The-Battle-of-the-Neighborhoods.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Big Data Integration and Processing/soccer-tweet-analysis.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Big Data Integration and Processing/spark-streaming.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Big Data Integration and Processing/spark-wordcount.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Capstone Project/pyspark-mllib-clustering.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Machine Learning/classification-in-spark.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Machine Learning/clustering.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Machine Learning/data-exploration-in-spark.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Machine Learning/handling-missing-values.ipynb"
"./Coursera_Bigdata_UCSD-master.zip.dir/Coursera_Bigdata_UCSD-master/Machine Learning/model-evaluation.ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/Battle of Neighborhoods - Week 1.ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/Capstone - The Battle of Neighborhoods - GN - Final.ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/The Battle of Neighborhoods - Week 2.ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/Toronto - Clustering Neighborhoods - PART 1 .ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/Toronto - Clustering Neighborhoods - Part 2.ipynb"
"./Coursera_Capstone-master.01.zip.dir/Coursera_Capstone-master/Toronto - Clustering Neighborhoods - PART 3.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Capstone Project - The Battle of Neighborhoods - Final.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Capstone Project - The Battle of Neighborhoods.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Coursera_Capstone.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Week 3 Assignment.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Week 3 Assignment Task 1.ipynb"
"./Coursera_Capstone-master.02.zip.dir/Coursera_Capstone-master/Week 3 Assignment Task 2.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Final Project/Data Cleaning/Cleaning.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Final Project/Data Scraping/meta data for zomato restaurants.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Final Project/Final Project Notebook/EDA and Project Notebook.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Week 3/capstone_project_Week_3_Part_1.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Week 3/Capstone_project_week3_part_2_.ipynb"
"./Coursera_Capstone-master.03.zip.dir/Coursera_Capstone-master/Week 3/Capstone_project_week3_part_3_.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/Finals/Extras4Visualization.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/Finals/Singapore_BOTN_final.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/Finals/StatisticalInference_BOTN.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/SegmentinAndClusteringNeighborhoods-Toronto.PART_3.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/SegmentingAndClusteringNeighborhoods-Toronto.PART_1.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/SegmentingAndClusteringNeighborhoods-Toronto.PART_2.ipynb"
"./Coursera_Capstone-master.04.zip.dir/Coursera_Capstone-master/week1-Intro_to_Capstone_Project.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Capstone project notebook.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Clustering on Toronto.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Data Collection.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Exploring venues in Chandigarh.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Exploring venues using Foursquare and Zomato.ipynb"
"./Coursera_Capstone-master.05.zip.dir/Coursera_Capstone-master/Getting coordinates.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/Coursera_Capstone.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/.ipynb"_checkpoints/Coursera_Capstone-checkpoint.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/.ipynb"_checkpoints/week3_part1-checkpoint.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/.ipynb"_checkpoints/week3_part2-checkpoint.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/.ipynb"_checkpoints/week3_part3-checkpoint.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/.ipynb"_checkpoints/week5_final_report-checkpoint.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/week3_part1.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/week3_part2.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/week3_part3.ipynb"
"./Coursera_Capstone-master.06.zip.dir/Coursera_Capstone-master/week5_final_report.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BattleOfTheNeighbourhoods.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-01-DataAcquisition.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-02-CrimesVisualisation.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-03-Inferential Statistics.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-04-Modelling.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-05-CombinedVisualisation.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/BOTN-06-Prediction.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/CapstoneProjectNotebook.ipynb"
"./Coursera_Capstone-master.07.zip.dir/Coursera_Capstone-master/NeighborhoodsToronto.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Coursera_cap_week1.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week3/week3_Neighbourhood_Segmentation.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week4/Capstone_Battle_of_Neighborhoods_Part1.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week5/Capstone_Week4_Part2.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week5/Capstone_Week4_Report.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week5/.ipynb"_checkpoints/Capstone_Week4_Part2-checkpoint.ipynb"
"./Coursera_Capstone-master.08.zip.dir/Coursera_Capstone-master/Week5/.ipynb"_checkpoints/Capstone_Week4_Report-checkpoint.ipynb"
"./Coursera_Capstone-master.09.zip.dir/Coursera_Capstone-master/Capstone Project.ipynb"
"./Coursera_Capstone-master.09.zip.dir/Coursera_Capstone-master/Coursera Capstone - London Property Recommendation.ipynb"
"./Coursera_Capstone-master.09.zip.dir/Coursera_Capstone-master/Explore Toronto neighborhoods.ipynb"
"./Coursera_Capstone-master.09.zip.dir/Coursera_Capstone-master/Scrape Wiki-page.ipynb"
"./Coursera_Capstone-master.09.zip.dir/Coursera_Capstone-master/Scrape Wiki-page & Join.ipynb"
"./Coursera_Capstone-master.10.zip.dir/Coursera_Capstone-master/Nattha's Coursera Capstone Project Notebook.ipynb"
"./Coursera_Capstone-master.10.zip.dir/Coursera_Capstone-master/Segmenting and Clustering Neighborhoods in Toronto.ipynb"
"./Coursera_Capstone-master.11.zip.dir/Coursera_Capstone-master/Capstone Proj.ipynb"
"./Coursera_Capstone-master.11.zip.dir/Coursera_Capstone-master/Coursera_Capstone.ipynb"
"./Coursera_Capstone-master.11.zip.dir/Coursera_Capstone-master/Segmenting and Clustering Neighborhoods in Toronto2.ipynb"
"./Coursera_Capstone-master.11.zip.dir/Coursera_Capstone-master/Segmenting and Clustering Neighborhoods in Toronto3.ipynb"
"./Coursera_Capstone-master.11.zip.dir/Coursera_Capstone-master/Segmenting and Clustering Neighborhoods in Toronto.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/Best_Classifier.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/Capstone Project.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/DP0701EN-2-2-1-Foursquare-API-py-v1.0.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/DP0701EN-3-3-2-Neighborhoods-New-York-py-v1.0.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/ManudJ_W1_N001.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/ML0101EN-Proj-Loan-answer-py-v1.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/Week3Assignment_002.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/Week3Assignment_003.ipynb"
"./Coursera_Capstone-master.12.zip.dir/Coursera_Capstone-master/Week3Assingment_001.ipynb"
"./coursera_capstone-master.zip.dir/coursera_capstone-master/Capstone_final_project.ipynb"
"./coursera_capstone-master.zip.dir/coursera_capstone-master/ML_Project Notebook.ipynb"
"./coursera_capstone-master.zip.dir/coursera_capstone-master/PeerReview1_Clustering_Toronto.ipynb"
"./coursera-data-science-master.zip.dir/coursera-data-science-master/Budapest Map.ipynb"
"./coursera-data-science-master.zip.dir/coursera-data-science-master/C9, Week3, 1 Toronto Hoods.ipynb"
"./coursera-data-science-master.zip.dir/coursera-data-science-master/C9, Week3, 2 Import Coordinates.ipynb"
"./coursera-data-science-master.zip.dir/coursera-data-science-master/C9, Week3, 3 Venues and Cluster.ipynb"
"./coursera-data-science-master.zip.dir/coursera-data-science-master/notebook_IBM_Data_Science_C9_HyKozfexS.ipynb"
"./coursera-ibm-ds-capstone-master.zip.dir/coursera-ibm-ds-capstone-master/Assignment-Notebook.ipynb"
"./coursera-ibm-ds-capstone-master.zip.dir/coursera-ibm-ds-capstone-master/Capstone_Analyze.ipynb"
"./coursera-ibm-ds-capstone-master.zip.dir/coursera-ibm-ds-capstone-master/Capstone_Intro.ipynb"
"./coursera-ibm-ds-capstone-master.zip.dir/coursera-ibm-ds-capstone-master/CapstoneProjectNotebook.ipynb"
"./coursera-ibm-ds-capstone-master.zip.dir/coursera-ibm-ds-capstone-master/Toronto_Neighborhood.ipynb"
"./ML0101EN-Proj-Loan-answer-py-v1.ipynb"
"./Segmenting-and-Clustering-Toronto.ipynb"
"./Stage 1 (1).ipynb"
"./Stage 1 (2).ipynb"
"./Stage 1.ipynb"
"./Stage 2 (1).ipynb"
"./Stage 2.ipynb"
"./The best classifier.ipynb"
